#!/usr/bin/env python3
"""Scans images/ and writes js/gallery-manifest.js, a flat list of exactly
which photos exist. Run this after adding/removing photos, then commit the
result. The page reads this instead of probing the server file-by-file for
every possible filename, which is what made first paint slow.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGE_EXTS = {"jpg", "jpeg", "png", "webp"}
VIDEO_EXTS = {"mp4", "mov", "webm"}

SERIES_GALLERIES = [
    "images/photography/portrait/",
    "images/photography/street/",
]
FLAT_GALLERIES = [
    "images/photography/film/",
    "images/painting/",
    "images/exhibition/",
]


def numbered_files(dir_path):
    if not os.path.isdir(dir_path):
        return []
    items = []
    for name in os.listdir(dir_path):
        stem, _, ext = name.rpartition(".")
        if not stem or not stem.isdigit():
            continue
        ext = ext.lower()
        if ext in IMAGE_EXTS or ext in VIDEO_EXTS:
            items.append((int(stem), name, ext in VIDEO_EXTS))
    items.sort(key=lambda t: t[0])
    return items


def build_series(base):
    abs_base = os.path.join(ROOT, base)
    if not os.path.isdir(abs_base):
        return []
    series_dirs = sorted(
        (d for d in os.listdir(abs_base) if d.startswith("series-")),
        key=lambda d: int(d.split("-")[1]),
    )
    series = []
    for d in series_dirs:
        frames = numbered_files(os.path.join(abs_base, d))
        if frames:
            series.append([f"{base}{d}/{name}" for _, name, _ in frames])
    return series


def build_flat(base):
    abs_base = os.path.join(ROOT, base)
    items = numbered_files(abs_base)
    return [{"url": f"{base}{name}", "isVideo": is_video} for _, name, is_video in items]


manifest = {}
for base in SERIES_GALLERIES:
    manifest[base] = {"type": "series", "series": build_series(base)}
for base in FLAT_GALLERIES:
    manifest[base] = {"type": "flat", "items": build_flat(base)}

out_path = os.path.join(ROOT, "js", "gallery-manifest.js")
with open(out_path, "w") as f:
    f.write("// Auto-generated by scripts/generate_manifest.py — do not edit by hand.\n")
    f.write("window.GALLERY_MANIFEST = ")
    f.write(json.dumps(manifest, indent=2, ensure_ascii=False))
    f.write(";\n")

for base, entry in manifest.items():
    count = len(entry["series"]) if entry["type"] == "series" else len(entry["items"])
    print(f"{base}: {count}")
print(f"Wrote {out_path}")
